#! /bin/bash

for original_name in *."$1";
do
	new_name=`echo $original_name | sed -e 's:^\(.*\)\.'"${1}"'$:\1\.'"${2}"':g'`; 
	echo "$original_name -> $new_name"

	mv $original_name $new_name ; 
done
